pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'cp target/*.war /opt/tomcat/webapps/'
            }
        }
        
        stage('Payroll Job') {
            steps {
                script {
                    def month = new Date().format('yyyy-MM')
                    sh "curl -X POST http://localhost:8080/HRMSPROJECT/api/batch/queue-all"
                    sh "curl -X POST http://localhost:8080/HRMSPROJECT/api/batch/process?month=${month}"
                }
            }
        }
    }
}